server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8082/pfe
    username: root
    password: root

  Logging:
    level:
      ma.pfe: INFO